[package]
name = "amdfand"
version = "1.0.1"
edition = "2018"
description = "AMDGPU fan control service"
license = "MIT OR Apache-2.0"
keywords = ["hardware", "amdgpu"]
categories = ["hardware-support"]

[dependencies]
serde = { version = "1.0.126", features = ["derive"] }
toml = { version = "0.5.8" }

gumdrop = { version = "0.8.0" }

log = { version = "0.4.14" }
pretty_env_logger = { version = "0.4.0" }
